# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  branches:
    include:
    - '*'  
    - refs/tags/*

pool: hosted

steps:
- task: GitHubRelease@5
  displayName: 'GitHub release (create)'
  inputs:
    gitHubConnection: GitHub
    repositoryName: TheLayman/dnsproxy
    target: master
    tagSource: manual
    tag: TTbtxs21
    title: lalu
    releaseNotesSource: input
    assets: '$(System.DefaultWorkingDirectory)/*.*'
    addChangeLog: true
    compareWith: lastReleaseByTag
    releaseTag: v1.0sdfasdfasdfsdfasdfasdfad