# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  branches:
    include:
    - '*'  
    - refs/tags/*

pool: hosted

steps:
- task: GitHubRelease@1
  displayName: 'GitHub release (create)'
  inputs:
    gitHubConnection: 'github connection 1'
    tagSource: gitTag
    releaseNotesSource: inline
    releaseNotesInline: 'Dude, What''s up? '
    addChangeLog: false
