# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  branches:
    include:
    - '*'  
    - refs/tags/*

pool: hosted

steps:
- task: GitHubRelease@6
  displayName: 'GitHub release (create)'
  inputs:
    gitHubConnection: GitHub
    repositoryName: TheLayman/dnsproxy
    target: master
    title: dodo
    releaseNotesSource: input
    assets: '$(System.DefaultWorkingDirectory)/*.*'
    changeLogCompareToRelease: lastNonDraftReleaseByTag
    changeLogCompareToReleaseTag: v33
    changeLogType: issueBased
    changeLogLabels: '{"labels": [{"label": "duplicate", "displayName": "Duplicate Stuff"}]}'
